### ISSUE TITLE
Array Size Feature. (32 EMG channels and 2000Hz sampling frequency)

### ISSUE THREAD

**Issue by Ankitadas22** [neuromechanist/hdEMG-Decomposition#2]
Hi,
      I am working with 32 EMG channels and a sampling frequency of 2000 Hz in OTBioLab+ Version 1.6.0. However, when I run the decomposition code in Matlab provided in the GitHub link for our data specifications, I encounter an error in the **'plot_SpikeTrain'** function. It seems that the provided code is configured for 64 EMG channels and a sampling frequency of 2048 Hz. 

 Your assistance in resolving this issue would be immensely helpful.
Thank you in advance!

**Comment by neuromechanist** [comment]
Thanks, Ankita, for the comment. The frequency should not have been an issue. In any case, this seems to be a very good, low-hanging improvement that I can make.

Stay tuned.

**Comment by Ankitadas22** [comment]
Yes sir. The problem was with the array size.

Thank you for your support.


Regards,

Ankita Das

**Comment by neuromechanist** [comment]
@Ankitadas22, please download and recheck the code. It should now work using the `arr` keyword.
Also, please be mindful of #1. I will check what is happening with that this week.
